// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace LivrariaControleEmprestimo.DATA.Models;

public partial class Emprestimo
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    public int ClienteId { get; set; }

    public int LivroId { get; set; }

    [Column("dataEmprestimo", TypeName = "datetime")]
    public DateTime? DataEmprestimo { get; set; }

    [Column("dataEntrega", TypeName = "datetime")]
    public DateTime? DataEntrega { get; set; }

    [Column("entregue")]
    public bool? Entregue { get; set; }

    [ForeignKey("ClienteId")]
    [InverseProperty("Emprestimo")]
    public virtual Cliente Cliente { get; set; }

    [ForeignKey("LivroId")]
    [InverseProperty("Emprestimo")]
    public virtual Livro Livro { get; set; }
}