// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace LivrariaControleEmprestimo.DATA.Models;

public partial class Livro
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Required]
    [Column("nome")]
    [StringLength(50)]
    public string Nome { get; set; }

    [Required]
    [Column("autor")]
    [StringLength(200)]
    [Unicode(false)]
    public string Autor { get; set; }

    [Required]
    [Column("editora")]
    [StringLength(100)]
    [Unicode(false)]
    public string Editora { get; set; }

    [Column("anoPublicacao", TypeName = "datetime")]
    public DateTime AnoPublicacao { get; set; }

    [Required]
    [Column("edicao")]
    [StringLength(50)]
    [Unicode(false)]
    public string Edicao { get; set; }

    [InverseProperty("IdLivroNavigation")]
    public virtual ICollection<Emprestimo> Emprestimo { get; set; } = new List<Emprestimo>();
}