// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace LivrariaControleEmprestimo.DATA.Models;

[Keyless]
public partial class ViewEmprestimo
{
    [Required]
    [StringLength(100)]
    [Unicode(false)]
    public string NomeCliente { get; set; }

    [Required]
    [StringLength(50)]
    public string NomeLivro { get; set; }

    [Column("id")]
    public int Id { get; set; }

    public int ClienteId { get; set; }

    public int LivroId { get; set; }

    [Column("dataEmprestimo", TypeName = "datetime")]
    public DateTime? DataEmprestimo { get; set; }

    [Column("dataEntrega", TypeName = "datetime")]
    public DateTime? DataEntrega { get; set; }

    [Column("entregue")]
    public bool? Entregue { get; set; }
}